/********************************** (C) COPYRIGHT *******************************
* File Name          : RGB.H
* Author             : WCH
* Version            : V1.0
* Date               : 2020/07/06
* Description        : CH545 RGB
*******************************************************************************/
#ifndef	__RGB_H__
#define __RGB_H__

#include "DEBUG.H"


void InitRGBLED(void);

#endif
